### ISSUE TITLE
Composing from another file results in undefined

### ISSUE THREAD

**Issue by NogsMPLS** [michalkvasnicak/babel-plugin-css-modules-transform#1]
given some css like this:
```css
.base {
  composes: inline-block from '../styles.css';
  color: red;
}
```
.babelrc like this:
```javascript
"plugins": [
        ["css-modules-transform", { "generateScopedName": "test_[name]__[local]" }]
    ]
``` 
the plugin outputs this:
```javascript
var _button = {
    'base': 'test_component__base undefined',
}
```
