### ISSUE TITLE
Relative urls are not resolved in extracted css

### ISSUE THREAD

**Issue by GreenGremlin** [michalkvasnicak/babel-plugin-css-modules-transform#100]
Given the following config:

```json
    "css-modules-transform", {
      "generateScopedName": "[name]__[local]___[hash:base64:5]",
      "extractCss": "./dist/styles.css",
    }
```

And the  following css:

```css
/* src/components/SpecialButton.css */
.button___3y7di {
    background-image: url('./buttonBackground.png');
}
```

I would expect output to contain relative urls, resolved to the output directory:

```css
/* dist/styles.css */
.SpecialButton__button___3y7di {
    background-image: url('./components/buttonBackground.png');
}
```

But I get this:

```css
/* dist/styles.css */
.SpecialButton__button___3y7di {
    background-image: url('./buttonBackground.png');
}
```

Is there something I'm missing?
