### ISSUE TITLE
Removing requirement for extension in import/composes

### ISSUE THREAD

**Issue by saiichihashimoto** [michalkvasnicak/babel-plugin-css-modules-transform#21]
When using babel-plugin-css-modules-transform (which has saved my life, btw), you can write something like this:

```js
// component.js
var styles = require('./styles'); // No extension
```

But this isn't possible:

```css
// styles.css
.some-class {
  composes: another-class from './global'; /* No extension */
}
```

This is required, currently:

```css
// styles.css
.some-class {
  composes: another-class from './global.css'; /* Extension */
}
```

Currently, webpack doesn't require the extension here and, to keep parity, it would make a lot of sense to not require it here either.
