### ISSUE TITLE
when less file has function, the styles props will be {}

### ISSUE THREAD

**Issue by nikogu** [michalkvasnicak/babel-plugin-css-modules-transform#67]
version: 1.2.7

```less
.clearfix(){}

.imgBlock {
    flex: 0 0 62.5%;
    width: 62.5%;
    padding-right: 152px;
    .clearfix();
}
```

=> babel css modules transform
```jsx
va style = {};
```

if remove `clearfix` will transform ok.
