### ISSUE TITLE
css-modules-transform + postcss + generateScopedName does not work as expecting

### ISSUE THREAD

**Issue by a-x-** [michalkvasnicak/babel-plugin-css-modules-transform#82]
input:
**a.css**:
```css
.foo { color: red; font-weight: bold; }
.bar { color: red; font-weight: normal; }
```
output:
**a.css**:
```css
.foo-XcD0 {font-weight: bold;}
.bar-wEd3 {color: red; font-weight: normal;}
.foo,.bar {color: red;} /* <<< generateScopedName omited in postcss optimized selector */
```
